[package]
name = "glfw_aegis"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "package"
path = "scripts/build_package.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
aegis = { path = "../aegis" }
